- id: prettier
  name: prettier
  entry: prettier --write
  language: node
  files: "\\.(\
    css|less|scss\
    |graphql|gql\
    |js|jsx\
    |json\
    |md|markdown|mdown|mkdn\
    |mdx\
    |ts|tsx\
    |vue\
    |yaml|yml\
    )$"
